collections:
  types:
    output: true

title: alex an blog
url:

defaults:
  - scope:
      path: ""
      type: "types"
    values:
      layout: "type"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

theme: minima

repository: fangana/fangana.github.io
