collections:
  categories:
    output: true

title: alex an blog
url:

defaults:
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

theme: jekyll-theme-dinky
repository: fangana/fangana.github.io
