collections:
  types:
    output: true

title: alex an blog
author: alex an
description: alex an
url:

defaults:
  - scope:
      path: ""
      type: "types"
    values:
      layout: "type"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

theme: brume

repository: fangana/fangana.github.io

color_scheme: azul
