collections:
  categories:
    output: true

title: alex an
description: alex an blog

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

theme: jekyll-theme-dinky
repository: fangana/fangana.github.io
